spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highLight_sql: true
        ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres