
spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highLight_sql: true
        ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres

auth:
  jwt:
    issuer: "yoong.com"
    secret: "sdvoejrlfvndkvoeowijnc123439mdslkdjj32"
    accessTokenExpirationHour: 168
    refreshTokenExpirationHour: 168
server:
  port: 80

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /index.html
    operationsSorter: alpha
    tagsSorter: alpha
    url: /v3/api-docs
    disable-swagger-default-url: true